//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL.ShoppingProductServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingProductServiceReference.IShoppingProductService")]
    public interface IShoppingProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/GetShopping_ProductForShoppingAndProdu" +
            "ct", ReplyAction="http://tempuri.org/IShoppingProductService/GetShopping_ProductForShoppingAndProdu" +
            "ctResponse")]
        LBCFUBL_WCF.DBO.Shopping_Product GetShopping_ProductForShoppingAndProduct(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/GetShopping_ProductForShoppingAndProdu" +
            "ct", ReplyAction="http://tempuri.org/IShoppingProductService/GetShopping_ProductForShoppingAndProdu" +
            "ctResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping_Product> GetShopping_ProductForShoppingAndProductAsync(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShopping", ReplyAction="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShoppingRespons" +
            "e")]
        LBCFUBL_WCF.DBO.Shopping_Product[] GetShopping_ProductsForShopping(LBCFUBL_WCF.DBO.Shopping shopping);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShopping", ReplyAction="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShoppingRespons" +
            "e")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping_Product[]> GetShopping_ProductsForShoppingAsync(LBCFUBL_WCF.DBO.Shopping shopping);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/CreateShopping_Product", ReplyAction="http://tempuri.org/IShoppingProductService/CreateShopping_ProductResponse")]
        void CreateShopping_Product(LBCFUBL_WCF.DBO.Product product, LBCFUBL_WCF.DBO.Shopping shopping, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/CreateShopping_Product", ReplyAction="http://tempuri.org/IShoppingProductService/CreateShopping_ProductResponse")]
        System.Threading.Tasks.Task CreateShopping_ProductAsync(LBCFUBL_WCF.DBO.Product product, LBCFUBL_WCF.DBO.Shopping shopping, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/DeleteShopping_Product", ReplyAction="http://tempuri.org/IShoppingProductService/DeleteShopping_ProductResponse")]
        bool DeleteShopping_Product(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/DeleteShopping_Product", ReplyAction="http://tempuri.org/IShoppingProductService/DeleteShopping_ProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteShopping_ProductAsync(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShoppingId", ReplyAction="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShoppingIdRespo" +
            "nse")]
        LBCFUBL_WCF.DBO.Shopping_Product[] GetShopping_ProductsForShoppingId(System.Guid shoppingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShoppingId", ReplyAction="http://tempuri.org/IShoppingProductService/GetShopping_ProductsForShoppingIdRespo" +
            "nse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping_Product[]> GetShopping_ProductsForShoppingIdAsync(System.Guid shoppingId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingProductServiceChannel : LBCFUBL.ShoppingProductServiceReference.IShoppingProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingProductServiceClient : System.ServiceModel.ClientBase<LBCFUBL.ShoppingProductServiceReference.IShoppingProductService>, LBCFUBL.ShoppingProductServiceReference.IShoppingProductService {
        
        public ShoppingProductServiceClient() {
        }
        
        public ShoppingProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LBCFUBL_WCF.DBO.Shopping_Product GetShopping_ProductForShoppingAndProduct(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product) {
            return base.Channel.GetShopping_ProductForShoppingAndProduct(shopping, product);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping_Product> GetShopping_ProductForShoppingAndProductAsync(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product) {
            return base.Channel.GetShopping_ProductForShoppingAndProductAsync(shopping, product);
        }
        
        public LBCFUBL_WCF.DBO.Shopping_Product[] GetShopping_ProductsForShopping(LBCFUBL_WCF.DBO.Shopping shopping) {
            return base.Channel.GetShopping_ProductsForShopping(shopping);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping_Product[]> GetShopping_ProductsForShoppingAsync(LBCFUBL_WCF.DBO.Shopping shopping) {
            return base.Channel.GetShopping_ProductsForShoppingAsync(shopping);
        }
        
        public void CreateShopping_Product(LBCFUBL_WCF.DBO.Product product, LBCFUBL_WCF.DBO.Shopping shopping, int number) {
            base.Channel.CreateShopping_Product(product, shopping, number);
        }
        
        public System.Threading.Tasks.Task CreateShopping_ProductAsync(LBCFUBL_WCF.DBO.Product product, LBCFUBL_WCF.DBO.Shopping shopping, int number) {
            return base.Channel.CreateShopping_ProductAsync(product, shopping, number);
        }
        
        public bool DeleteShopping_Product(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product) {
            return base.Channel.DeleteShopping_Product(shopping, product);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteShopping_ProductAsync(LBCFUBL_WCF.DBO.Shopping shopping, LBCFUBL_WCF.DBO.Product product) {
            return base.Channel.DeleteShopping_ProductAsync(shopping, product);
        }
        
        public LBCFUBL_WCF.DBO.Shopping_Product[] GetShopping_ProductsForShoppingId(System.Guid shoppingId) {
            return base.Channel.GetShopping_ProductsForShoppingId(shoppingId);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping_Product[]> GetShopping_ProductsForShoppingIdAsync(System.Guid shoppingId) {
            return base.Channel.GetShopping_ProductsForShoppingIdAsync(shoppingId);
        }
    }
}
