//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL.ShoppingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingServiceReference.IShoppingService")]
    public interface IShoppingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppings", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsResponse")]
        LBCFUBL_WCF.DBO.Shopping[] GetShoppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppings", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping[]> GetShoppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsBeforeDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsBeforeDateResponse")]
        LBCFUBL_WCF.DBO.Shopping[] GetShoppingsBeforeDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsBeforeDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsBeforeDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping[]> GetShoppingsBeforeDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsAfterDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsAfterDateResponse")]
        LBCFUBL_WCF.DBO.Shopping[] GetShoppingsAfterDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsAfterDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsAfterDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping[]> GetShoppingsAfterDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/CreateShopping", ReplyAction="http://tempuri.org/IShoppingService/CreateShoppingResponse")]
        void CreateShopping(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/CreateShopping", ReplyAction="http://tempuri.org/IShoppingService/CreateShoppingResponse")]
        System.Threading.Tasks.Task CreateShoppingAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/CreateShoppingWithProducts", ReplyAction="http://tempuri.org/IShoppingService/CreateShoppingWithProductsResponse")]
        void CreateShoppingWithProducts(System.DateTime date, LBCFUBL_WCF.DBO.Shopping_Product[] shopping_products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/CreateShoppingWithProducts", ReplyAction="http://tempuri.org/IShoppingService/CreateShoppingWithProductsResponse")]
        System.Threading.Tasks.Task CreateShoppingWithProductsAsync(System.DateTime date, LBCFUBL_WCF.DBO.Shopping_Product[] shopping_products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/DeleteShopping", ReplyAction="http://tempuri.org/IShoppingService/DeleteShoppingResponse")]
        bool DeleteShopping(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/DeleteShopping", ReplyAction="http://tempuri.org/IShoppingService/DeleteShoppingResponse")]
        System.Threading.Tasks.Task<bool> DeleteShoppingAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingFromId", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingFromIdResponse")]
        LBCFUBL_WCF.DBO.Shopping GetShoppingFromId(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingFromId", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingFromIdResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping> GetShoppingFromIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/DeleteShoppingFromId", ReplyAction="http://tempuri.org/IShoppingService/DeleteShoppingFromIdResponse")]
        bool DeleteShoppingFromId(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/DeleteShoppingFromId", ReplyAction="http://tempuri.org/IShoppingService/DeleteShoppingFromIdResponse")]
        System.Threading.Tasks.Task<bool> DeleteShoppingFromIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingTotalCost", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingTotalCostResponse")]
        double GetShoppingTotalCost(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingTotalCost", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingTotalCostResponse")]
        System.Threading.Tasks.Task<double> GetShoppingTotalCostAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingServiceChannel : LBCFUBL.ShoppingServiceReference.IShoppingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingServiceClient : System.ServiceModel.ClientBase<LBCFUBL.ShoppingServiceReference.IShoppingService>, LBCFUBL.ShoppingServiceReference.IShoppingService {
        
        public ShoppingServiceClient() {
        }
        
        public ShoppingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LBCFUBL_WCF.DBO.Shopping[] GetShoppings() {
            return base.Channel.GetShoppings();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping[]> GetShoppingsAsync() {
            return base.Channel.GetShoppingsAsync();
        }
        
        public LBCFUBL_WCF.DBO.Shopping[] GetShoppingsBeforeDate(System.DateTime date) {
            return base.Channel.GetShoppingsBeforeDate(date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping[]> GetShoppingsBeforeDateAsync(System.DateTime date) {
            return base.Channel.GetShoppingsBeforeDateAsync(date);
        }
        
        public LBCFUBL_WCF.DBO.Shopping[] GetShoppingsAfterDate(System.DateTime date) {
            return base.Channel.GetShoppingsAfterDate(date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping[]> GetShoppingsAfterDateAsync(System.DateTime date) {
            return base.Channel.GetShoppingsAfterDateAsync(date);
        }
        
        public void CreateShopping(System.DateTime date) {
            base.Channel.CreateShopping(date);
        }
        
        public System.Threading.Tasks.Task CreateShoppingAsync(System.DateTime date) {
            return base.Channel.CreateShoppingAsync(date);
        }
        
        public void CreateShoppingWithProducts(System.DateTime date, LBCFUBL_WCF.DBO.Shopping_Product[] shopping_products) {
            base.Channel.CreateShoppingWithProducts(date, shopping_products);
        }
        
        public System.Threading.Tasks.Task CreateShoppingWithProductsAsync(System.DateTime date, LBCFUBL_WCF.DBO.Shopping_Product[] shopping_products) {
            return base.Channel.CreateShoppingWithProductsAsync(date, shopping_products);
        }
        
        public bool DeleteShopping(System.DateTime date) {
            return base.Channel.DeleteShopping(date);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteShoppingAsync(System.DateTime date) {
            return base.Channel.DeleteShoppingAsync(date);
        }
        
        public LBCFUBL_WCF.DBO.Shopping GetShoppingFromId(System.Guid id) {
            return base.Channel.GetShoppingFromId(id);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Shopping> GetShoppingFromIdAsync(System.Guid id) {
            return base.Channel.GetShoppingFromIdAsync(id);
        }
        
        public bool DeleteShoppingFromId(System.Guid id) {
            return base.Channel.DeleteShoppingFromId(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteShoppingFromIdAsync(System.Guid id) {
            return base.Channel.DeleteShoppingFromIdAsync(id);
        }
        
        public double GetShoppingTotalCost(System.Guid id) {
            return base.Channel.GetShoppingTotalCost(id);
        }
        
        public System.Threading.Tasks.Task<double> GetShoppingTotalCostAsync(System.Guid id) {
            return base.Channel.GetShoppingTotalCostAsync(id);
        }
    }
}
