//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL.ShoppingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shopping", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Shopping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Shopping_Product[] Shopping_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Shopping_Product[] Shopping_Product {
            get {
                return this.Shopping_ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.Shopping_ProductField, value) != true)) {
                    this.Shopping_ProductField = value;
                    this.RaisePropertyChanged("Shopping_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shopping_Product", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Shopping_Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Shopping ShoppingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid id_productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid id_shoppingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Shopping Shopping {
            get {
                return this.ShoppingField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingField, value) != true)) {
                    this.ShoppingField = value;
                    this.RaisePropertyChanged("Shopping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id_product {
            get {
                return this.id_productField;
            }
            set {
                if ((this.id_productField.Equals(value) != true)) {
                    this.id_productField = value;
                    this.RaisePropertyChanged("id_product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id_shopping {
            get {
                return this.id_shoppingField;
            }
            set {
                if ((this.id_shoppingField.Equals(value) != true)) {
                    this.id_shoppingField = value;
                    this.RaisePropertyChanged("id_shopping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Purchase[] PurchasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Shopping_Product[] Shopping_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cost_with_marginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cost_without_marginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Purchase[] Purchases {
            get {
                return this.PurchasesField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchasesField, value) != true)) {
                    this.PurchasesField = value;
                    this.RaisePropertyChanged("Purchases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Shopping_Product[] Shopping_Product {
            get {
                return this.Shopping_ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.Shopping_ProductField, value) != true)) {
                    this.Shopping_ProductField = value;
                    this.RaisePropertyChanged("Shopping_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cost_with_margin {
            get {
                return this.cost_with_marginField;
            }
            set {
                if ((this.cost_with_marginField.Equals(value) != true)) {
                    this.cost_with_marginField = value;
                    this.RaisePropertyChanged("cost_with_margin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cost_without_margin {
            get {
                return this.cost_without_marginField;
            }
            set {
                if ((this.cost_without_marginField.Equals(value) != true)) {
                    this.cost_without_marginField = value;
                    this.RaisePropertyChanged("cost_without_margin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purchase", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Purchase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid id_prodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id_prod {
            get {
                return this.id_prodField;
            }
            set {
                if ((this.id_prodField.Equals(value) != true)) {
                    this.id_prodField = value;
                    this.RaisePropertyChanged("id_prod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Account[] AccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.Purchase[] PurchasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Account[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.Purchase[] Purchases {
            get {
                return this.PurchasesField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchasesField, value) != true)) {
                    this.PurchasesField = value;
                    this.RaisePropertyChanged("Purchases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int role {
            get {
                return this.roleField;
            }
            set {
                if ((this.roleField.Equals(value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.ShoppingServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double argentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.ShoppingServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double argent {
            get {
                return this.argentField;
            }
            set {
                if ((this.argentField.Equals(value) != true)) {
                    this.argentField = value;
                    this.RaisePropertyChanged("argent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingServiceReference.IShoppingService")]
    public interface IShoppingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppings", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsResponse")]
        LBCFUBL.ShoppingServiceReference.Shopping[] GetShoppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppings", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsResponse")]
        System.Threading.Tasks.Task<LBCFUBL.ShoppingServiceReference.Shopping[]> GetShoppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsBeforeDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsBeforeDateResponse")]
        LBCFUBL.ShoppingServiceReference.Shopping[] GetShoppingsBeforeDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsBeforeDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsBeforeDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL.ShoppingServiceReference.Shopping[]> GetShoppingsBeforeDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsAfterDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsAfterDateResponse")]
        LBCFUBL.ShoppingServiceReference.Shopping[] GetShoppingsAfterDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/GetShoppingsAfterDate", ReplyAction="http://tempuri.org/IShoppingService/GetShoppingsAfterDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL.ShoppingServiceReference.Shopping[]> GetShoppingsAfterDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/CreateShopping", ReplyAction="http://tempuri.org/IShoppingService/CreateShoppingResponse")]
        void CreateShopping(System.DateTime date, LBCFUBL.ShoppingServiceReference.Shopping_Product[] shopping_products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/CreateShopping", ReplyAction="http://tempuri.org/IShoppingService/CreateShoppingResponse")]
        System.Threading.Tasks.Task CreateShoppingAsync(System.DateTime date, LBCFUBL.ShoppingServiceReference.Shopping_Product[] shopping_products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/DeleteShopping", ReplyAction="http://tempuri.org/IShoppingService/DeleteShoppingResponse")]
        bool DeleteShopping(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingService/DeleteShopping", ReplyAction="http://tempuri.org/IShoppingService/DeleteShoppingResponse")]
        System.Threading.Tasks.Task<bool> DeleteShoppingAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingServiceChannel : LBCFUBL.ShoppingServiceReference.IShoppingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingServiceClient : System.ServiceModel.ClientBase<LBCFUBL.ShoppingServiceReference.IShoppingService>, LBCFUBL.ShoppingServiceReference.IShoppingService {
        
        public ShoppingServiceClient() {
        }
        
        public ShoppingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LBCFUBL.ShoppingServiceReference.Shopping[] GetShoppings() {
            return base.Channel.GetShoppings();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL.ShoppingServiceReference.Shopping[]> GetShoppingsAsync() {
            return base.Channel.GetShoppingsAsync();
        }
        
        public LBCFUBL.ShoppingServiceReference.Shopping[] GetShoppingsBeforeDate(System.DateTime date) {
            return base.Channel.GetShoppingsBeforeDate(date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL.ShoppingServiceReference.Shopping[]> GetShoppingsBeforeDateAsync(System.DateTime date) {
            return base.Channel.GetShoppingsBeforeDateAsync(date);
        }
        
        public LBCFUBL.ShoppingServiceReference.Shopping[] GetShoppingsAfterDate(System.DateTime date) {
            return base.Channel.GetShoppingsAfterDate(date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL.ShoppingServiceReference.Shopping[]> GetShoppingsAfterDateAsync(System.DateTime date) {
            return base.Channel.GetShoppingsAfterDateAsync(date);
        }
        
        public void CreateShopping(System.DateTime date, LBCFUBL.ShoppingServiceReference.Shopping_Product[] shopping_products) {
            base.Channel.CreateShopping(date, shopping_products);
        }
        
        public System.Threading.Tasks.Task CreateShoppingAsync(System.DateTime date, LBCFUBL.ShoppingServiceReference.Shopping_Product[] shopping_products) {
            return base.Channel.CreateShoppingAsync(date, shopping_products);
        }
        
        public bool DeleteShopping(System.DateTime date) {
            return base.Channel.DeleteShopping(date);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteShoppingAsync(System.DateTime date) {
            return base.Channel.DeleteShoppingAsync(date);
        }
    }
}
