//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserFromLogin", ReplyAction="http://tempuri.org/IUserService/GetUserFromLoginResponse")]
        LBCFUBL_WCF.DBO.User GetUserFromLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserFromLogin", ReplyAction="http://tempuri.org/IUserService/GetUserFromLoginResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.User> GetUserFromLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        LBCFUBL_WCF.DBO.User CreateUser(string login, string password, int role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.User> CreateUserAsync(string login, string password, int role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        bool DeleteUser(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        LBCFUBL_WCF.DBO.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.User[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserMoney", ReplyAction="http://tempuri.org/IUserService/GetUserMoneyResponse")]
        double GetUserMoney(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserMoney", ReplyAction="http://tempuri.org/IUserService/GetUserMoneyResponse")]
        System.Threading.Tasks.Task<double> GetUserMoneyAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersMoneys", ReplyAction="http://tempuri.org/IUserService/GetUsersMoneysResponse")]
        System.Tuple<string, double>[] GetUsersMoneys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersMoneys", ReplyAction="http://tempuri.org/IUserService/GetUsersMoneysResponse")]
        System.Threading.Tasks.Task<System.Tuple<string, double>[]> GetUsersMoneysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Block", ReplyAction="http://tempuri.org/IUserService/BlockResponse")]
        void Block(string login, [System.ServiceModel.MessageParameterAttribute(Name="block")] bool block1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Block", ReplyAction="http://tempuri.org/IUserService/BlockResponse")]
        System.Threading.Tasks.Task BlockAsync(string login, bool block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAccountHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUserAccountHistoryResultResponse")]
        LBCFUBL_WCF.DBO.Get_User_Account_History_Result[] GetUserAccountHistoryResult(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAccountHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUserAccountHistoryResultResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Account_History_Result[]> GetUserAccountHistoryResultAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserPurchaseHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUserPurchaseHistoryResultResponse")]
        LBCFUBL_WCF.DBO.Get_User_Purchase_History_Result[] GetUserPurchaseHistoryResult(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserPurchaseHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUserPurchaseHistoryResultResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Purchase_History_Result[]> GetUserPurchaseHistoryResultAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersAccountHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUsersAccountHistoryResultResponse")]
        LBCFUBL_WCF.DBO.Get_Users_Accounts_History_Result[] GetUsersAccountHistoryResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersAccountHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUsersAccountHistoryResultResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Accounts_History_Result[]> GetUsersAccountHistoryResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersPurchasesHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUsersPurchasesHistoryResultResponse")]
        LBCFUBL_WCF.DBO.Get_Users_Purchases_History_Result[] GetUsersPurchasesHistoryResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersPurchasesHistoryResult", ReplyAction="http://tempuri.org/IUserService/GetUsersPurchasesHistoryResultResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Purchases_History_Result[]> GetUsersPurchasesHistoryResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAccountDayHistory", ReplyAction="http://tempuri.org/IUserService/GetUserAccountDayHistoryResponse")]
        LBCFUBL_WCF.DBO.Get_User_Account_Day_History_Result[] GetUserAccountDayHistory(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAccountDayHistory", ReplyAction="http://tempuri.org/IUserService/GetUserAccountDayHistoryResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Account_Day_History_Result[]> GetUserAccountDayHistoryAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserPurchaseDayHistory", ReplyAction="http://tempuri.org/IUserService/GetUserPurchaseDayHistoryResponse")]
        LBCFUBL_WCF.DBO.Get_User_Purchase_Day_History_Result[] GetUserPurchaseDayHistory(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserPurchaseDayHistory", ReplyAction="http://tempuri.org/IUserService/GetUserPurchaseDayHistoryResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Purchase_Day_History_Result[]> GetUserPurchaseDayHistoryAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAccountsDayHistory", ReplyAction="http://tempuri.org/IUserService/GetAccountsDayHistoryResponse")]
        LBCFUBL_WCF.DBO.Get_Users_Accounts_Day_History_Result[] GetAccountsDayHistory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAccountsDayHistory", ReplyAction="http://tempuri.org/IUserService/GetAccountsDayHistoryResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Accounts_Day_History_Result[]> GetAccountsDayHistoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPurchasesDayHistory", ReplyAction="http://tempuri.org/IUserService/GetPurchasesDayHistoryResponse")]
        LBCFUBL_WCF.DBO.Get_Users_Purchases_Day_History_Result[] GetPurchasesDayHistory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPurchasesDayHistory", ReplyAction="http://tempuri.org/IUserService/GetPurchasesDayHistoryResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Purchases_Day_History_Result[]> GetPurchasesDayHistoryAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : LBCFUBL.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<LBCFUBL.UserServiceReference.IUserService>, LBCFUBL.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LBCFUBL_WCF.DBO.User GetUserFromLogin(string login) {
            return base.Channel.GetUserFromLogin(login);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.User> GetUserFromLoginAsync(string login) {
            return base.Channel.GetUserFromLoginAsync(login);
        }
        
        public LBCFUBL_WCF.DBO.User CreateUser(string login, string password, int role) {
            return base.Channel.CreateUser(login, password, role);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.User> CreateUserAsync(string login, string password, int role) {
            return base.Channel.CreateUserAsync(login, password, role);
        }
        
        public bool DeleteUser(string login) {
            return base.Channel.DeleteUser(login);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(string login) {
            return base.Channel.DeleteUserAsync(login);
        }
        
        public LBCFUBL_WCF.DBO.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public double GetUserMoney(string login) {
            return base.Channel.GetUserMoney(login);
        }
        
        public System.Threading.Tasks.Task<double> GetUserMoneyAsync(string login) {
            return base.Channel.GetUserMoneyAsync(login);
        }
        
        public System.Tuple<string, double>[] GetUsersMoneys() {
            return base.Channel.GetUsersMoneys();
        }
        
        public System.Threading.Tasks.Task<System.Tuple<string, double>[]> GetUsersMoneysAsync() {
            return base.Channel.GetUsersMoneysAsync();
        }
        
        public void Block(string login, bool block1) {
            base.Channel.Block(login, block1);
        }
        
        public System.Threading.Tasks.Task BlockAsync(string login, bool block) {
            return base.Channel.BlockAsync(login, block);
        }
        
        public LBCFUBL_WCF.DBO.Get_User_Account_History_Result[] GetUserAccountHistoryResult(string login) {
            return base.Channel.GetUserAccountHistoryResult(login);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Account_History_Result[]> GetUserAccountHistoryResultAsync(string login) {
            return base.Channel.GetUserAccountHistoryResultAsync(login);
        }
        
        public LBCFUBL_WCF.DBO.Get_User_Purchase_History_Result[] GetUserPurchaseHistoryResult(string login) {
            return base.Channel.GetUserPurchaseHistoryResult(login);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Purchase_History_Result[]> GetUserPurchaseHistoryResultAsync(string login) {
            return base.Channel.GetUserPurchaseHistoryResultAsync(login);
        }
        
        public LBCFUBL_WCF.DBO.Get_Users_Accounts_History_Result[] GetUsersAccountHistoryResult() {
            return base.Channel.GetUsersAccountHistoryResult();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Accounts_History_Result[]> GetUsersAccountHistoryResultAsync() {
            return base.Channel.GetUsersAccountHistoryResultAsync();
        }
        
        public LBCFUBL_WCF.DBO.Get_Users_Purchases_History_Result[] GetUsersPurchasesHistoryResult() {
            return base.Channel.GetUsersPurchasesHistoryResult();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Purchases_History_Result[]> GetUsersPurchasesHistoryResultAsync() {
            return base.Channel.GetUsersPurchasesHistoryResultAsync();
        }
        
        public LBCFUBL_WCF.DBO.Get_User_Account_Day_History_Result[] GetUserAccountDayHistory(string login) {
            return base.Channel.GetUserAccountDayHistory(login);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Account_Day_History_Result[]> GetUserAccountDayHistoryAsync(string login) {
            return base.Channel.GetUserAccountDayHistoryAsync(login);
        }
        
        public LBCFUBL_WCF.DBO.Get_User_Purchase_Day_History_Result[] GetUserPurchaseDayHistory(string login) {
            return base.Channel.GetUserPurchaseDayHistory(login);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_User_Purchase_Day_History_Result[]> GetUserPurchaseDayHistoryAsync(string login) {
            return base.Channel.GetUserPurchaseDayHistoryAsync(login);
        }
        
        public LBCFUBL_WCF.DBO.Get_Users_Accounts_Day_History_Result[] GetAccountsDayHistory() {
            return base.Channel.GetAccountsDayHistory();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Accounts_Day_History_Result[]> GetAccountsDayHistoryAsync() {
            return base.Channel.GetAccountsDayHistoryAsync();
        }
        
        public LBCFUBL_WCF.DBO.Get_Users_Purchases_Day_History_Result[] GetPurchasesDayHistory() {
            return base.Channel.GetPurchasesDayHistory();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Users_Purchases_Day_History_Result[]> GetPurchasesDayHistoryAsync() {
            return base.Channel.GetPurchasesDayHistoryAsync();
        }
    }
}
