//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL_WCF.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string login { get; set; }
        public double argent { get; set; }
        public System.DateTime date { get; set; }
        public int id { get; set; }
    
        public virtual User User { get; set; }
    }
}
