//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL_WCF.DBO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class lbcfublEntities : DbContext
    {
        public lbcfublEntities()
            : base("name=lbcfublEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Shopping> Shoppings { get; set; }
        public virtual DbSet<Shopping_Product> Shopping_Product { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Nullable<double>> Get_User_Depenses(string user_login)
        {
            var user_loginParameter = user_login != null ?
                new ObjectParameter("user_login", user_login) :
                new ObjectParameter("user_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Get_User_Depenses", user_loginParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> Get_User_Money(string user_login)
        {
            var user_loginParameter = user_login != null ?
                new ObjectParameter("user_login", user_login) :
                new ObjectParameter("user_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Get_User_Money", user_loginParameter);
        }
    
        public virtual ObjectResult<Get_Users_Money_Result> Get_Users_Money()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Users_Money_Result>("Get_Users_Money");
        }
    
        public virtual ObjectResult<Get_User_Account_History_Result> Get_User_Account_History(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Account_History_Result>("Get_User_Account_History", loginParameter);
        }
    
        public virtual ObjectResult<Get_User_Purchase_History_Result> Get_User_Purchase_History(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Purchase_History_Result>("Get_User_Purchase_History", loginParameter);
        }
    
        public virtual ObjectResult<Get_Users_Accounts_History_Result> Get_Users_Accounts_History()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Users_Accounts_History_Result>("Get_Users_Accounts_History");
        }
    
        public virtual ObjectResult<Get_Users_Purchases_History_Result> Get_Users_Purchases_History()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Users_Purchases_History_Result>("Get_Users_Purchases_History");
        }
    
        public virtual ObjectResult<Get_Stock_For_Date_Result> Get_Stock_For_Date(Nullable<System.DateTime> datett)
        {
            var datettParameter = datett.HasValue ?
                new ObjectParameter("datett", datett) :
                new ObjectParameter("datett", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Stock_For_Date_Result>("Get_Stock_For_Date", datettParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> Get_Purchase_Total(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Get_Purchase_Total", idParameter);
        }
    
        public virtual ObjectResult<Get_User_Account_Day_History_Result> Get_User_Account_Day_History(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Account_Day_History_Result>("Get_User_Account_Day_History", loginParameter);
        }
    
        public virtual ObjectResult<Get_User_Money_History_Result> Get_User_Money_History(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Money_History_Result>("Get_User_Money_History", loginParameter);
        }
    
        public virtual ObjectResult<Get_User_Purchase_Day_History_Result> Get_User_Purchase_Day_History(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Purchase_Day_History_Result>("Get_User_Purchase_Day_History", loginParameter);
        }
    
        public virtual ObjectResult<Get_Users_Accounts_Day_History_Result> Get_Users_Accounts_Day_History()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Users_Accounts_Day_History_Result>("Get_Users_Accounts_Day_History");
        }
    
        public virtual ObjectResult<Get_Users_Purchases_Day_History_Result> Get_Users_Purchases_Day_History()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Users_Purchases_Day_History_Result>("Get_Users_Purchases_Day_History");
        }
    }
}
