//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL_WCF.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Product
    {
        public System.Guid id_shopping { get; set; }
        public System.Guid id_product { get; set; }
        public int number { get; set; }
        public int id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shopping Shopping { get; set; }
    }
}
