//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL.PurchaseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purchase", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Purchase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid id_prodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id_prod {
            get {
                return this.id_prodField;
            }
            set {
                if ((this.id_prodField.Equals(value) != true)) {
                    this.id_prodField = value;
                    this.RaisePropertyChanged("id_prod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Purchase[] PurchasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Shopping_Product[] Shopping_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cost_with_marginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cost_without_marginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Purchase[] Purchases {
            get {
                return this.PurchasesField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchasesField, value) != true)) {
                    this.PurchasesField = value;
                    this.RaisePropertyChanged("Purchases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Shopping_Product[] Shopping_Product {
            get {
                return this.Shopping_ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.Shopping_ProductField, value) != true)) {
                    this.Shopping_ProductField = value;
                    this.RaisePropertyChanged("Shopping_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cost_with_margin {
            get {
                return this.cost_with_marginField;
            }
            set {
                if ((this.cost_with_marginField.Equals(value) != true)) {
                    this.cost_with_marginField = value;
                    this.RaisePropertyChanged("cost_with_margin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cost_without_margin {
            get {
                return this.cost_without_marginField;
            }
            set {
                if ((this.cost_without_marginField.Equals(value) != true)) {
                    this.cost_without_marginField = value;
                    this.RaisePropertyChanged("cost_without_margin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Account[] AccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Purchase[] PurchasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Account[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Purchase[] Purchases {
            get {
                return this.PurchasesField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchasesField, value) != true)) {
                    this.PurchasesField = value;
                    this.RaisePropertyChanged("Purchases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int role {
            get {
                return this.roleField;
            }
            set {
                if ((this.roleField.Equals(value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shopping_Product", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Shopping_Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Shopping ShoppingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid id_productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid id_shoppingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Shopping Shopping {
            get {
                return this.ShoppingField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingField, value) != true)) {
                    this.ShoppingField = value;
                    this.RaisePropertyChanged("Shopping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id_product {
            get {
                return this.id_productField;
            }
            set {
                if ((this.id_productField.Equals(value) != true)) {
                    this.id_productField = value;
                    this.RaisePropertyChanged("id_product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id_shopping {
            get {
                return this.id_shoppingField;
            }
            set {
                if ((this.id_shoppingField.Equals(value) != true)) {
                    this.id_shoppingField = value;
                    this.RaisePropertyChanged("id_shopping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shopping", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Shopping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.Shopping_Product[] Shopping_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.Shopping_Product[] Shopping_Product {
            get {
                return this.Shopping_ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.Shopping_ProductField, value) != true)) {
                    this.Shopping_ProductField = value;
                    this.RaisePropertyChanged("Shopping_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/LBCFUBL_WCF.DBO")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LBCFUBL.PurchaseServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double argentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LBCFUBL.PurchaseServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double argent {
            get {
                return this.argentField;
            }
            set {
                if ((this.argentField.Equals(value) != true)) {
                    this.argentField = value;
                    this.RaisePropertyChanged("argent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseServiceReference.IPurchaseService")]
    public interface IPurchaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLogin", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginResponse")]
        LBCFUBL.PurchaseServiceReference.Purchase[] GetPurchasesForLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLogin", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginResponse")]
        System.Threading.Tasks.Task<LBCFUBL.PurchaseServiceReference.Purchase[]> GetPurchasesForLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDateResponse")]
        LBCFUBL.PurchaseServiceReference.Purchase[] GetPurchasesForLoginBeforeDate(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL.PurchaseServiceReference.Purchase[]> GetPurchasesForLoginBeforeDateAsync(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDateResponse")]
        LBCFUBL.PurchaseServiceReference.Purchase[] GetPurchasesForLoginAfterDate(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL.PurchaseServiceReference.Purchase[]> GetPurchasesForLoginAfterDateAsync(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/CreatePurchase", ReplyAction="http://tempuri.org/IPurchaseService/CreatePurchaseResponse")]
        void CreatePurchase(string login, System.DateTime date, System.Guid id_prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/CreatePurchase", ReplyAction="http://tempuri.org/IPurchaseService/CreatePurchaseResponse")]
        System.Threading.Tasks.Task CreatePurchaseAsync(string login, System.DateTime date, System.Guid id_prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/DeletePurchase", ReplyAction="http://tempuri.org/IPurchaseService/DeletePurchaseResponse")]
        bool DeletePurchase(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/DeletePurchase", ReplyAction="http://tempuri.org/IPurchaseService/DeletePurchaseResponse")]
        System.Threading.Tasks.Task<bool> DeletePurchaseAsync(string login, System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseServiceChannel : LBCFUBL.PurchaseServiceReference.IPurchaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseServiceClient : System.ServiceModel.ClientBase<LBCFUBL.PurchaseServiceReference.IPurchaseService>, LBCFUBL.PurchaseServiceReference.IPurchaseService {
        
        public PurchaseServiceClient() {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LBCFUBL.PurchaseServiceReference.Purchase[] GetPurchasesForLogin(string login) {
            return base.Channel.GetPurchasesForLogin(login);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL.PurchaseServiceReference.Purchase[]> GetPurchasesForLoginAsync(string login) {
            return base.Channel.GetPurchasesForLoginAsync(login);
        }
        
        public LBCFUBL.PurchaseServiceReference.Purchase[] GetPurchasesForLoginBeforeDate(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginBeforeDate(login, date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL.PurchaseServiceReference.Purchase[]> GetPurchasesForLoginBeforeDateAsync(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginBeforeDateAsync(login, date);
        }
        
        public LBCFUBL.PurchaseServiceReference.Purchase[] GetPurchasesForLoginAfterDate(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginAfterDate(login, date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL.PurchaseServiceReference.Purchase[]> GetPurchasesForLoginAfterDateAsync(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginAfterDateAsync(login, date);
        }
        
        public void CreatePurchase(string login, System.DateTime date, System.Guid id_prod) {
            base.Channel.CreatePurchase(login, date, id_prod);
        }
        
        public System.Threading.Tasks.Task CreatePurchaseAsync(string login, System.DateTime date, System.Guid id_prod) {
            return base.Channel.CreatePurchaseAsync(login, date, id_prod);
        }
        
        public bool DeletePurchase(string login, System.DateTime date) {
            return base.Channel.DeletePurchase(login, date);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePurchaseAsync(string login, System.DateTime date) {
            return base.Channel.DeletePurchaseAsync(login, date);
        }
    }
}
