//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCFUBL.PurchaseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseServiceReference.IPurchaseService")]
    public interface IPurchaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchases", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesResponse")]
        LBCFUBL_WCF.DBO.Purchase[] GetPurchases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchases", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLogin", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginResponse")]
        LBCFUBL_WCF.DBO.Purchase[] GetPurchasesForLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLogin", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesForLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDateResponse")]
        LBCFUBL_WCF.DBO.Purchase[] GetPurchasesForLoginBeforeDate(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginBeforeDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesForLoginBeforeDateAsync(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDateResponse")]
        LBCFUBL_WCF.DBO.Purchase[] GetPurchasesForLoginAfterDate(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDate", ReplyAction="http://tempuri.org/IPurchaseService/GetPurchasesForLoginAfterDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesForLoginAfterDateAsync(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/CreatePurchase", ReplyAction="http://tempuri.org/IPurchaseService/CreatePurchaseResponse")]
        void CreatePurchase(string login, System.DateTime date, System.Guid id_prod, string added_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/CreatePurchase", ReplyAction="http://tempuri.org/IPurchaseService/CreatePurchaseResponse")]
        System.Threading.Tasks.Task CreatePurchaseAsync(string login, System.DateTime date, System.Guid id_prod, string added_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/DeletePurchase", ReplyAction="http://tempuri.org/IPurchaseService/DeletePurchaseResponse")]
        bool DeletePurchase(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/DeletePurchase", ReplyAction="http://tempuri.org/IPurchaseService/DeletePurchaseResponse")]
        System.Threading.Tasks.Task<bool> DeletePurchaseAsync(string login, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetStocksForDate", ReplyAction="http://tempuri.org/IPurchaseService/GetStocksForDateResponse")]
        LBCFUBL_WCF.DBO.Get_Stock_For_Date_Result[] GetStocksForDate(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetStocksForDate", ReplyAction="http://tempuri.org/IPurchaseService/GetStocksForDateResponse")]
        System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Stock_For_Date_Result[]> GetStocksForDateAsync(System.DateTime dt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseServiceChannel : LBCFUBL.PurchaseServiceReference.IPurchaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseServiceClient : System.ServiceModel.ClientBase<LBCFUBL.PurchaseServiceReference.IPurchaseService>, LBCFUBL.PurchaseServiceReference.IPurchaseService {
        
        public PurchaseServiceClient() {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LBCFUBL_WCF.DBO.Purchase[] GetPurchases() {
            return base.Channel.GetPurchases();
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesAsync() {
            return base.Channel.GetPurchasesAsync();
        }
        
        public LBCFUBL_WCF.DBO.Purchase[] GetPurchasesForLogin(string login) {
            return base.Channel.GetPurchasesForLogin(login);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesForLoginAsync(string login) {
            return base.Channel.GetPurchasesForLoginAsync(login);
        }
        
        public LBCFUBL_WCF.DBO.Purchase[] GetPurchasesForLoginBeforeDate(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginBeforeDate(login, date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesForLoginBeforeDateAsync(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginBeforeDateAsync(login, date);
        }
        
        public LBCFUBL_WCF.DBO.Purchase[] GetPurchasesForLoginAfterDate(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginAfterDate(login, date);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Purchase[]> GetPurchasesForLoginAfterDateAsync(string login, System.DateTime date) {
            return base.Channel.GetPurchasesForLoginAfterDateAsync(login, date);
        }
        
        public void CreatePurchase(string login, System.DateTime date, System.Guid id_prod, string added_by) {
            base.Channel.CreatePurchase(login, date, id_prod, added_by);
        }
        
        public System.Threading.Tasks.Task CreatePurchaseAsync(string login, System.DateTime date, System.Guid id_prod, string added_by) {
            return base.Channel.CreatePurchaseAsync(login, date, id_prod, added_by);
        }
        
        public bool DeletePurchase(string login, System.DateTime date) {
            return base.Channel.DeletePurchase(login, date);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePurchaseAsync(string login, System.DateTime date) {
            return base.Channel.DeletePurchaseAsync(login, date);
        }
        
        public LBCFUBL_WCF.DBO.Get_Stock_For_Date_Result[] GetStocksForDate(System.DateTime dt) {
            return base.Channel.GetStocksForDate(dt);
        }
        
        public System.Threading.Tasks.Task<LBCFUBL_WCF.DBO.Get_Stock_For_Date_Result[]> GetStocksForDateAsync(System.DateTime dt) {
            return base.Channel.GetStocksForDateAsync(dt);
        }
    }
}
